#include "NU32.h"
#include "direction.h"
#include "bluetooth.h"
#include <stdio.h>

#define BUF_SIZE 200


void __ISR(_UART_1_VECTOR, IPL1SOFT) IntUart1Handler(void) {
    NU32_LED2 = 0;
  if (IFS0bits.U1RXIF) {       // check if interrupt generated by a RX event
    cmd();       // send the received data out
    IFS0bits.U1RXIF = 0;       // clear the RX interrupt flag
  } else if(IFS0bits.U1TXIF) { // if it is a TX interrupt
  } else if(IFS0bits.U1EIF) {  // if it is an error interrupt. check U3STA for reason
  }
}


int main(){
  NU32_LED2 = 1;
  NU32_LED2 = 1;
  __builtin_disable_interrupts();
  pwmInit();
  btInit();
  U1STAbits.URXISEL = 0x0; // RX interrupt when receive buffer not empty
  IFS0bits.U1RXIF = 0;     // clear the rx interrupt flag.  for
                         // tx or error interrupts you would also need to clear
                         // the respective flags
  IPC6bits.U1IP = 1;       // interrupt priority
  IEC0bits.U1RXIE = 1;
  __builtin_enable_interrupts();
  //dir(1);

  while(1){
    cmd();

  }
  return 0;
}
